name: Build and Package Release

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'
        
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build Avalonia app
      run: dotnet build --configuration Release
      
    - name: Publish Avalonia app
      run: dotnet publish -c Release -o app_publish
        
    - name: Create ZIP archive
      run: zip -r release.zip app_publish
          
    - name: Upload ZIP archive
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
